name: "Bug Report"
description: "Report a bug or unexpected behavior in busykube"
title: "[Bug] <Short Description>"
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in `busykube`. Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the bug."
      placeholder: "e.g., When I run `busykube kubectl get pods`, I get an error message..."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Run `busykube <command>`
        2. Observe the error
