blank_issues_enabled: true
contact_links:
  - name: "Support"
    url: "https://github.com/jacobtomlinson/busykube/discussions"
    about: "If you have questions or need help, please start a discussion instead of opening an issue."
